name: Cut Release Branch

on:
  schedule:
    # This schedule is in UTC, 3pm EST is 7pm UTC during daylight saving time and 8pm UTC otherwise.
    # Adjust accordingly if needed.
    - cron: "0 19 * * 5"

jobs:
  cut_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Cut Release Branch
        run: |
          # Assuming versioning format is x.y.z and you want to bump the z part.
          # Adjust accordingly if your versioning is different.
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          NEW_TAG=${LATEST_TAG%.*}.$((${LATEST_TAG##*.} + 1))

          git checkout develop
          git checkout -b release/$NEW_TAG
          git push origin release/$NEW_TAG

      - name: Print New Release Branch
        run: echo "New release branch is release/$NEW_TAG"